name: Update GroupIcons_Emoji.json

on:
  push:
    paths:
      - 'icon/emoji/**/*.png'

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update JSON file
        run: |
          # 构建 jq 命令的输入字符串
          input=$(find icon/emoji -name "*.png" -exec echo '[{"name": "'{}'", "url": "https://raw.githubusercontent.com/mphin/GroupIcons/main/'{}'"}]' \; | jq -s add)

          # 使用 jq 更新 GroupIcons_Emoji.json 文件
          echo "$input" | jq '{name: "GroupIconsEmoji", icons: ., description: "策略组Emoji图标集，收集好看的Emoji表情，图像来源于Emojiall"}' > GroupIcons_Emoji.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add GroupIcons_Emoji.json
          git commit -m "Update GroupIcons_Emoji.json"
          git push
