name: Update GroupIcons_Emoji.json

on:
  push:
    paths:
      - 'icon/emoji/**/*.png'
  delete:
    paths:
      - 'icon/emoji/**/*.png'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Update GroupIcons_Emoji.json
        run: |
          jq -s '.[0] + {"icons": .[1]}' GroupIcons_Emoji.json $(find . -name "*.png" -type f | awk -F/ '{sub("^./",""); printf "{\"name\": \"%s\", \"url\": \"https://raw.githubusercontent.com/mphin/GroupIcons/main/%s\"}\n", $NF, $0}') > updated.json
          mv updated.json GroupIcons_Emoji.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update GroupIcons_Emoji.json" --allow-empty
          git push
