name: Process Conf Files

on:
  push:
    branches:
      - main

jobs:
  process_conf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script
      run: |
        tmp_folder="tmp"
        script_folder="script"
        plugin_folder="plugin"
        mkdir -p "$tmp_folder" "$script_folder" "$plugin_folder"
        
        for conf_file in $tmp_folder/*.conf; do
            if [ -f "$conf_file" ]; then
                download_url=$(grep '^#!url =' "$conf_file" | sed 's/^#!url = //')
                download_file="$script_folder/$(basename "$conf_file" .conf).js"
                wget -O "$download_file" "$download_url"

                name=$(grep '^#!name =' "$conf_file" | sed 's/^#!name = //')
                desc=$(grep '^#!desc =' "$conf_file" | sed 's/^#!desc = //')
                openUrl=$(grep '^#!openUrl =' "$conf_file" | sed 's/^#!openUrl = //')
                author=$(grep '^#!author =' "$conf_file" | sed 's/^#!author = //')
                homepage=$(grep '^#!homepage =' "$conf_file" | sed 's/^#!homepage = //')
                icon=$(grep '^#!icon =' "$conf_file" | sed 's/^#!icon = //')
                date=$(grep -oE '\d{4}([-/.年])\d{1,2}\1\d{1,2}' "$download_file" || grep '^#!date =' "$conf_file" | sed 's/^#!date = //')
                echo "$date"

                plugin_file="$plugin_folder/$(basename "$conf_file" .conf).plugin"
                echo "#!name = $name" > "$plugin_file"
                echo "#!desc = $desc" >> "$plugin_file"
                echo "#!openUrl = $openUrl" >> "$plugin_file"
                echo "#!author = $author" >> "$plugin_file"
                echo "#!homepage = $homepage" >> "$plugin_file"
                echo "#!icon = $icon" >> "$plugin_file"
                echo "#!date = $date" >> "$plugin_file"

                mitm=$(grep '^\[MITM\]' "$conf_file" | sed 's/^\[MITM\]//' || grep -i '^\[MITM\]' "$download_file" | sed 's/^\[MITM\]//')
                script=$(grep '^\[Script\]' "$conf_file" | sed 's/^\[Script\]//' || grep -i '^\[Script\]' "$download_file" | sed 's/^\[Script\]//')

                echo -e "\n[MITM]\n$mitm" >> "$plugin_file"
                echo -e "\n[Script]\n$script" >> "$plugin_file"
            fi
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m "Update plugin files"
        git push
