name: Update Recent Rule File

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update rules file
        run: |
          sed -i "s#更新：.*#更新：$(date +'%Y年%m月%d日%H:%M:%S')#" rules/*.list
          rule_count=$(grep -c 'DOMAIN' rules/*.list)
          sed -i "s#数量：.*#数量：$rule_count#" rules/*.list

      - name: Commit and push changes
        run: |
          git config --local user.email "632450362@qq.com"
          git config --local user.name "mphin"
          git add .
          git commit -m "Update recent rule file"
          git push
