name: Update List
on:
  push:
    branches:
      - main
    paths:
      - 'rules/*.list'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time zone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update List
        run: |
          # 获取当前时间
          current_date=$(TZ=Asia/Shanghai date '+%Y年%m月%d日%H:%M:%S')
          
          # 统计非空行和非注释行的数量
          count=$(grep -v -e '^$' -e '^#' ${{ github.event.inputs.list_file }} | wc -l)
          # 更新文件内容
          sed -i "s/^# 更新：.*/# 更新：$current_date/" ${{ github.event.inputs.list_file }}
          sed -i "s/^# 数量：.*/# 数量：$count/" ${{ github.event.inputs.list_file }}
      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update list files [skip ci]"
          git push
