name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Update README
        run: |
          # Get current date and time in Beijing timezone
          new_date=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H:%M:%S')

          # Replace the update time in README.md
          sed -i "s/更新时间：.*/更新时间：$new_date/" README.md

          # Commit and push changes
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update README with current time"
          git push origin main
